config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :albums
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :body, presence: true
    validates :images, presence: true
    has_many_attached :images
    
    has_many :taggings
    has_many :tags, through: :taggings, dependent: :destroy
    def all_tags=(names)
        self.tags = names.split(",").map do |name|
            Tag.where(tag_name: name.strip).first_or_create!
        end
      end
      
      def all_tags
        self.tags.map(&:tag_name).join(", ")
      end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :albums, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @q = Album.ransack(params[:q])
    
    @albums = current_user.albums
    @albums = @q.result.includes(:tags, :taggings)
  end

  def show

    @album = Album.find(params[:id])

  end

  def new
    
    @album = current_user.albums.build

  end

  def create
    
    @album = current_user.albums.build(album_params)

    if @album.save

      redirect_to root_path

    else
      render :new
    end
    
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to albums_path
  end


  def edit
    @album = Album.find(params[:id])
  end


  def update
    @album = Album.find_by(id: params[:id])
    
    if @album.update(album_params)
      redirect_to albums_path
    else
      render :edit
    end
  end

  def correct_user
    @album = current_user.albums.find_by(id: params[:id])
    redirect_to root_path, notice: "Not Allowed To Use This Record" if @album.nil? 
  end

  private

  def album_params
    params.require(:album).permit(:title, :body, :user_id, :published, :all_tags, images: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Album.ransack(params[:q])
    @albums = Album.where(published:true)
    @albums = @q.result.includes(:tags, :taggings)
  end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<%= form_with model: @album do |form| %>
    <div>
        <%= form.text_field :title, placeholder: "Title", class: "form-control mb-4"%>
    </div>

    <div>
        <%= form.text_field :body, placeholder: "description", class: "form-control mb-4"%>
    </div>

    <div>
        <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
    </div>

    <div class="mb-4">
        <%= form.file_field :images, multiple: true, class: "btn btn-outline-secondary" %>
    </div>

    <div class="mb-4">
      <%= form.text_field :all_tags, placeholder: "Add #tags", class: "form-control mb-4" %>
    </div>

    <div class="mb-4">
        <%= form.check_box :published%>
        <label for="flexSwitchCheckDefault">Publish Now?</label>
    </div>

    <div class="d-grid gap-2 col-6 mx-auto mb-3">
        <input type="submit" name="commit" value="Create Album" data-disable-with="Create Album" class="btn btn-primary">
    </div>

<% end %>

app/views/albums/edit.html.erb
<div class="container-fluid py-4 d-flex justify-content-center ">
    <div class="loginbox shadow p-3 mb-5 bg-body rounded">

        <h1 class="mb-4 d-flex justify-content-center">Update Album</h1>

        <%= render "form", album: @album %>

    </div>
</div>

app/views/albums/index.html.erb
<h1 class="d-flex justify-content-center publishedAblumHead mb-1">Published Album Below</h1>
<div class="d-flex justify-content-center mb-4">
    <form class="d-flex">
        <%= search_form_for @q do |f| %>
        <%= f.search_field :tags_tag_name_cont, class: "form-control me-2", placeholder: "search #tags"  %>
        <%= f.submit "search", class: "btn btn-outline-success"%>
        <% end %>
    </form>
</div>

<div class="row">



    <% @albums.each do|album|%>

    <div class="col-sm-12 col-md-4 d-flex justify-content-around mb-5 ">
        <div class="card shadow p-3 mb-5 bg-body rounded " style="width: 18rem;">
            <%= image_tag (album.images.first), class: "card-img-top" %>
            <div class="card-body cardcol">
                <h3 class="card-title"><%= album.title%></h3>
                <h5 class="card-text"><%= album.body%></h5>
                <p class="card-text">#{<%= album.all_tags%>}</p>
                <div class="btn-group d-flex justify-content-center">
                    <%= link_to "Show", album_path(album), class: "btn btn-success btn-sm"%>
                    <%if user_signed_in? %>
                    <%= link_to "Delete", album_path(album),
                                    method: :delete,
                                    data: { confirm: "Are you sure?" } , class: "btn btn-danger btn-sm"%>
                    <%= link_to "EditAlbum", edit_album_path(album) , class: "btn btn-warning btn-sm"%>

                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <%end%>
</div>

app/views/albums/new.html.erb
<div class="container-fluid py-4 d-flex justify-content-center ">
    <div class="loginbox shadow p-3 mb-5 bg-body rounded">

        <h1 class="mb-4 d-flex justify-content-center">New Album</h1>

        <%= render "form", album: @album %>

    </div>
</div>

app/views/albums/show.html.erb
<h1 class="d-flex justify-content-center">
    <%= @album.title %>
</h1>
<h5 class="d-flex justify-content-center mb-5">
    <%= @album.body %> 
    &nbsp &nbsp
    #{<%= @album.all_tags %>}
</h5>


<div class="row">

    <% (0...@album.images.count).each do |image| %>

    <div class="col-sm-12 col-md-4 d-flex justify-content-around mb-5">
        <div class="card" style="width: 18rem;">

            <%= image_tag (@album.images[image]), class: "card-img-top img-fluid m-auto"%>

        </div>
    </div>

    <% end %>

</div>

app/views/home/_headerFile.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to "Gallery", root_path, :class => 'navbar-brand'  %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%if user_signed_in? %>
                    <%= link_to "Add Your Album", new_album_path, :class => 'nav-link'  %>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%if user_signed_in? %>
                    <%= link_to "My Albums", albums_path, :class => 'nav-link'  %>

                    <% end %>
                </li>


            </ul>

            <p class="navbar-text float-right">

            <ul class="navbar-nav">

                <li class="nav-item">

                    <% if user_signed_in? %>
                    <!-- Logged in as <strong><%= current_user.email %></strong>. -->

                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
                </li>

                <li class="nav-item">
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'%>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
                </li>
                <li class="nav-item">
                    <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
                </li>
                <% end %>
            </ul>
            </p>
        </div>
    </div>
</nav>

app/views/home/formAddAlbum.html.erb
<h1>New Album</h1>

<%= form_with model: @album  do |form| %>
  <div>
    <%= form.label :Album_Name %><br>
    <%= form.text_field :Album_Name %>
  </div>

  <div>
    <%= form.label :Caption %><br>
    <%= form.text_field :Caption %>
  </div>

<div>
<%= form.label :"Do You Want To Publish This Album?" %>
<%= form.check_box :checkBox %>
</div>

<div>   
<input type="file" id="img" name="img" accept="image/*" multiple>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1 class="d-flex justify-content-center publishedAblumHead mb-1">Published Album Below</h1>

<div class="d-flex justify-content-center mb-4">
    <form class="d-flex">
        <%= search_form_for @q do |f| %>
        <%= f.search_field :tags_tag_name_cont, class: "form-control me-2", placeholder: "search #tags"  %>
        <%= f.submit "search", class: "btn btn-outline-success"%>
        <% end %>
    </form>
</div>

<div class="row">



    <% @albums.each do|album|%>

    <div class="col-sm-12 col-md-4 d-flex justify-content-around mb-5">
        <div class="card shadow p-3 mb-5 bg-body rounded" style="width: 18rem;">

            <%= image_tag (album.images.first), class: "card-img-top" %>

            <div class="card-body">
                <h3 class="card-title"><%= album.title%></h3>
                <h5 class="card-text"><%= album.body%></h5>
                <p class="card-text">#{<%= album.all_tags%>}</p>
                <div class="btn-group d-flex justify-content-center">
                    <%= link_to "Show", album_path(album), class: "btn btn-success btn-sm"%>
                </div>
            </div>
        </div>
    </div>
    <%end%>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap" rel="stylesheet">
    <title>Gallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

    <!-- Header Code -->
    <%= render 'home/headerFile' %>

    <div class="container-fluid">
        <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
        <% end %>


        <%if user_signed_in? %>

        <%= render 'home/addAlbumButton' %>
        <% end %>


        <%= yield %>



    </div>




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>

</html>